version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_DRIVER: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: synapsis_db
      DB_USER: postgres
      DB_PASSWORD: root
      API_PORT: 8080
      JWT_SECRET: yafireyhan-secret
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: synapsis_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
