CREATE TABLE "users" (
                         "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "guid" varchar(36) NOT NULL,
                         "name" varchar(255) DEFAULT null,
                         "email" varchar(255) NOT NULL,
                         "password" text NOT NULL,
                         "role" VARCHAR CHECK (role IN ('BUYER', 'SELLER'))
);