ALTER TABLE carts
    ADD CONSTRAINT unique_carts_guid UNIQUE (guid);

CREATE TABLE "checkouts"
(
    "id"   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "guid" varchar(36) NOT NULL,
    "user_guid" varchar(36) NOT NULL,
    "cart_guid" varchar(36) NOT NULL,
    "qty" int NOT NULL,
    "created_at" timestamp default current_timestamp,
    "updated_at" timestamp default current_timestamp,
    "deleted_at" timestamp,
    CONSTRAINT fk_user_checkout FOREIGN KEY (user_guid) REFERENCES users(guid),
    CONSTRAINT fk_cart_checkout FOREIGN KEY (cart_guid) REFERENCES carts(guid)
)