ALTER TABLE users
    ADD CONSTRAINT unique_users_guid UNIQUE (guid);

ALTER TABLE products
    ADD CONSTRAINT unique_products_guid UNIQUE (guid);


CREATE TABLE "carts"
(
    "id"   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "guid" varchar(36) NOT NULL,
    "user_guid" varchar(36) NOT NULL,
    "product_guid" varchar(36) NOT NULL,
    "qty" int NOT NULL,
    "created_at" timestamp default current_timestamp,
    "updated_at" timestamp default current_timestamp,
    "deleted_at" timestamp,
    CONSTRAINT fk_user_cart FOREIGN KEY (user_guid) REFERENCES users(guid),
    CONSTRAINT fk_product_cart FOREIGN KEY (product_guid) REFERENCES products(guid)
)