ALTER TABLE checkouts
    RENAME TO checkouts_old;

DROP TABLE checkouts_old;

CREATE TABLE "checkouts"
(
    "id"   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "guid" varchar(36) NOT NULL,
    "user_guid" varchar(36) NOT NULL,
    "cart_guid" varchar(36) NOT NULL,
    "order_date" timestamp DEFAULT current_timestamp,
    "total_price" decimal(10,2) NOT NULL,
    "status" VARCHAR CHECK (status IN ('PENDING', 'PAID')),
    "created_at" timestamp default current_timestamp,
    "updated_at" timestamp default current_timestamp,
    "deleted_at" timestamp,
    CONSTRAINT fk_user_checkout FOREIGN KEY (user_guid) REFERENCES users(guid),
    CONSTRAINT fk_cart_checkout FOREIGN KEY (cart_guid) REFERENCES carts(guid)
)